/**
 * Created by Игорь on 03.01.2016.
 */

export const USERS_ADD_USER = 'USERS_ADD_USER';
export const USERS_UPDATE_USER = 'USERS_UPDATE_USER';
export const USERS_GET_USERS = 'USERS_GET_USERS';
export const USERS_DELETE_USER = 'USERS_DELETE_USER';
export const USERS_START_LOADING = 'USERS_START_LOADING';
export const USERS_STOP_LOADING = 'USERS_STOP_LOADING';

export const LANGUAGE_SET_LANGUAGE = 'LANGUAGE_SET_LANGUAGE';
export const LANGUAGE_GET_LANGUAGE = 'LANGUAGE_GET_LANGUAGE';
export const LANGUAGE_START_LOADING = 'LANGUAGE_START_LOADING';
export const LANGUAGE_STOP_LOADING = 'LANGUAGE_STOP_LOADING';